// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

function clearBrokenAuthToken() {
  if (typeof window === 'undefined') return;

  try {
    const host = new URL(SUPABASE_URL).host;
    const projectRef = host.split('.')[0];
    const authKey = `sb-${projectRef}-auth-token`;
    const raw = localStorage.getItem(authKey);
    if (!raw) return;

    try {
      const parsed = JSON.parse(raw);
      // Only clear if token is completely malformed (missing user.id)
      // Do NOT clear valid tokens just because refresh_token is missing
      if (parsed && typeof parsed === 'object') {
        // Check for valid session structure
        const hasValidSession = 
          (parsed?.user?.id && typeof parsed.user.id === 'string') ||
          (parsed?.currentSession?.user?.id && typeof parsed.currentSession.user.id === 'string');
        
        if (!hasValidSession) {
          localStorage.removeItem(authKey);
        }
      } else {
        localStorage.removeItem(authKey);
      }
    } catch (parseError) {
      // If JSON is invalid, clear it
      localStorage.removeItem(authKey);
    }
  } catch {
    // If token JSON or URL parsing is invalid, clear old auth entries to recover.
    Object.keys(localStorage)
      .filter((key) => key.startsWith('sb-') && key.endsWith('-auth-token'))
      .forEach((key) => {
        try {
          const raw = localStorage.getItem(key);
          if (!raw) return;
          const parsed = JSON.parse(raw);
          const hasValidSession = 
            (parsed?.user?.id && typeof parsed.user.id === 'string') ||
            (parsed?.currentSession?.user?.id && typeof parsed.currentSession.user.id === 'string');
          if (!hasValidSession) {
            localStorage.removeItem(key);
          }
        } catch {
          localStorage.removeItem(key);
        }
      });
  }
}

clearBrokenAuthToken();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});