// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

function hasUsableSession(parsed: unknown): boolean {
  if (!parsed || typeof parsed !== 'object') return false;

  const root = parsed as Record<string, unknown>;
  const session = (root.currentSession && typeof root.currentSession === 'object'
    ? (root.currentSession as Record<string, unknown>)
    : root) as Record<string, unknown>;

  const user = session.user && typeof session.user === 'object'
    ? (session.user as Record<string, unknown>)
    : root.user && typeof root.user === 'object'
      ? (root.user as Record<string, unknown>)
      : null;

  const userId = user?.id;
  const accessToken = session.access_token ?? root.access_token;
  const refreshToken = session.refresh_token ?? root.refresh_token;

  return (
    typeof userId === 'string' && userId.length > 0 &&
    typeof accessToken === 'string' && accessToken.length > 0 &&
    typeof refreshToken === 'string' && refreshToken.length > 0
  );
}

function clearBrokenAuthToken() {
  if (typeof window === 'undefined') return;

  try {
    const host = new URL(SUPABASE_URL).host;
    const projectRef = host.split('.')[0];
    const authKey = `sb-${projectRef}-auth-token`;
    const raw = localStorage.getItem(authKey);
    if (!raw) return;

    try {
      const parsed = JSON.parse(raw);
      if (!hasUsableSession(parsed)) {
        localStorage.removeItem(authKey);
      }
    } catch (parseError) {
      // If JSON is invalid, clear it
      localStorage.removeItem(authKey);
    }
  } catch {
    // If token JSON or URL parsing is invalid, clear old auth entries to recover.
    Object.keys(localStorage)
      .filter((key) => key.startsWith('sb-') && key.endsWith('-auth-token'))
      .forEach((key) => {
        try {
          const raw = localStorage.getItem(key);
          if (!raw) return;
          const parsed = JSON.parse(raw);
          if (!hasUsableSession(parsed)) {
            localStorage.removeItem(key);
          }
        } catch {
          localStorage.removeItem(key);
        }
      });
  }
}

clearBrokenAuthToken();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});